/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Caneta bic = new Caneta();

        System.out.println(bic.isAberta());
        bic.trocarEstado();
        System.out.println(bic.isAberta());
        bic.definirCor("Azul");
        System.out.println(bic.isCor());
    }
}
