/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);

        while (leitor.hasNext()) {
            String linha = leitor.nextLine().toUpperCase();
            System.out.println(linha);
        }

        leitor.close();
    }
}
