/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import ads.poo.animais.Animal;
import ads.poo.animais.Ornitorrinco;
import ads.poo.animais.Oviparo;

public class App {
    public static void main(String[] args) {
        Animal bernardo = new Ornitorrinco("Bernardo");

        System.out.println(((Oviparo)bernardo).botarOvo());
        System.out.println(new Ornitorrinco("Bernardo").botarOvo());
    }
}
