/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String aux;
        char char1;
        char char2;
        char char3;
        int cont = 0;

        while (scanner.hasNext()) {
            aux = scanner.nextLine().toUpperCase();
            char1 = aux.charAt(0);
            char2 = aux.charAt(1);
            char3 = aux.charAt(2);
            System.out.printf(" %s \u2502 %s \u2502 %s\n", char1, char2, char3);
            if (cont != 2) {
                System.out.printf("\u2500\u2500\u2500\u253C\u2500\u2500\u2500\u253C\u2500\u2500\u2500\n");
            }
            cont++;
        }

        scanner.close();
    }
}
